[package]
name = "benches-lib"
edition = "2024"

[dependencies]
allocator-api2 = "0.2.21"
blink-alloc = "0.3.1"
bump-scope = { path = "../../..", features = ["allocator-api2-02"] }
bumpalo = { version = "3.19.0", features = ["allocator-api2"] }
paste = "1.0.15"
