name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust_channel: ["1.64.0", "stable", "nightly"]
        feature_set: ["--no-default-features"]
        include:
          - rust_channel: "nightly"
            feature_set: "--all-features"
    steps:
    - name: Install rustup
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal
    - name: Install rust channel
      run: rustup install ${{matrix.rust_channel}} && rustup default ${{matrix.rust_channel}}
    - uses: actions/checkout@v4
    - name: Run tests (no features)
      run: cargo test --verbose
    - name: Run tests (features)
      run: cargo test --verbose ${{matrix.feature_set}}
  miri:
    runs-on: ubuntu-latest
    env:
      MIRIFLAGS: "-Zmiri-strict-provenance -Zmiri-ignore-leaks"    
    steps:
    - name: Install rustup
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain nightly -y
    - name: Install miri
      run: rustup toolchain install nightly --allow-downgrade --profile minimal --component miri
    - uses: actions/checkout@v4
    - name: Run miri
      run: cargo miri test --all-features
  benches:
    runs-on: ubuntu-latest
    steps:
    - name: Install rustup
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --profile=minimal
    - name: Install rust nightly
      run: rustup install nightly && rustup default nightly
    - uses: actions/checkout@v4
    - name: Check that benches build
      run: cargo check --benches --all-features
    
