name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt --all -- --check
      - run: cd crates/fuzzing-support && cargo fmt --all -- --check
      - run: cd crates/test-fallibility && cargo fmt --all -- --check
      - run: cd crates/tests-from-std && cargo fmt --all -- --check
      - run: cd fuzz && cargo fmt --all -- --check
  check-msrv:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@1.64.0
      - run: cargo check --no-default-features
      - run: cargo check --features serde,zerocopy-08,allocator-api2-02
  check-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with: 
          components: clippy
      - run: cargo clippy --tests --no-default-features
      - run: cargo clippy --tests --features serde,zerocopy-08,allocator-api2-02,allocator-api2-03
  check-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with: 
          components: clippy
      - run: cargo clippy --tests --no-default-features
      - run: cargo clippy --tests --features serde,zerocopy-08,allocator-api2-02,allocator-api2-03
      - run: cargo clippy --tests --benches --all-features
      - run: cd crates/test-hashbrown && cargo clippy
      - run: cd crates/test-hashbrown && cargo clippy --all-features
      - run: cd crates/tests-from-std && cargo clippy
      - run: cd crates/test-fallibility && cargo clippy
      - run: cd crates/callgrind-benches && cargo clippy
  test-stable:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --features serde,zerocopy-08,allocator-api2-02,allocator-api2-03
  test-nightly:
    runs-on: ubuntu-latest
    env:
      MIRIFLAGS: "-Zmiri-strict-provenance"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: miri
      - run: cargo test --all-features
      - run: cargo miri test --all-features
      - run: cd crates/test-hashbrown && cargo test
      - run: cd crates/test-hashbrown && cargo test --all-features
      - run: cd crates/test-hashbrown && cargo miri test
      - run: cd crates/test-hashbrown && cargo miri test --all-features
      - run: cd crates/tests-from-std && cargo test
      - run: cd crates/tests-from-std && cargo miri test
      - run: cd crates/fuzzing-support && cargo test
      - run: cd crates/fuzzing-support && cargo miri test
  minimal-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly
      - uses: taiki-e/install-action@cargo-hack
      - uses: taiki-e/install-action@cargo-minimal-versions
      - uses: Swatinem/rust-cache@v2
      - run: cargo minimal-versions check
      - run: cargo minimal-versions check --all-features
