name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  format:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: format bump-scope
        run: cargo fmt --all -- --check
      - name: format fuzzing-support
        run: cd crates/fuzzing-support && cargo fmt --all -- --check
      - name: format inspect-asm
        run: cd crates/inspect-asm && cargo fmt --all -- --check
      - name: format test-fallibility
        run: cd crates/test-fallibility && cargo fmt --all -- --check
      - name: format fuzz
        run: cd fuzz && cargo fmt --all -- --check
  clippy:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: ["1.64.0", "stable", "nightly"]
        features: ["--no-default-features"]
        tests: [""]
        include:
          - toolchain: "nightly"
            features: "--all-features"
            tests: "--tests"
        exclude:
          - toolchain: "nightly"
            tests: ""
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{matrix.toolchain}}
        components: clippy
    - run: cargo clippy --all ${{matrix.tests}}      
    - run: cargo clippy --all ${{matrix.tests}} ${{matrix.features}}
  clippy-benches:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: clippy
    - run: cargo clippy --benches --all-features
  test:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      MIRIFLAGS: "-Zmiri-strict-provenance" 
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: miri
    - run: cargo test --all-features
    - run: cargo miri test --all-features
    
